<?php
/** Pussycat Mart landing page. Uses native WooCommerce products and cart actions. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
$products = function_exists( 'wc_get_products' ) ? wc_get_products( array( 'status' => 'publish', 'limit' => 4, 'orderby' => 'menu_order', 'order' => 'ASC' ) ) : array();
?>
<main class="site-main" id="top">
<section class="hero"><div class="container hero-grid"><div><span class="kicker">The purrfect donation</span><h1>The <em>purrfect</em> choice for your <span>cat.</span></h1><p class="lede">We don't just sell products — we give back. Every Pussycat Mart order sends 10% straight to cat rescues and no-kill shelters, then ships direct to your door.</p><div class="hero-actions"><a class="button" href="#shop">Shop the shelf</a><a class="button alt" href="#giveback">How we give back</a></div></div><div><img class="hero-image" src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/hero-cat.jpg' ); ?>" width="1600" height="1100" fetchpriority="high" decoding="async" alt="Happy rescue cat lounging beside toys and a food bowl"></div></div></section>
<section class="section" id="shop"><div class="container"><div class="section-heading"><div><span class="kicker">100% cat-approved</span><h2>Build your order 🧺</h2></div><p class="section-copy">Tap add to cart. Spoil the cat. Free shipping over $75.</p></div>
<?php if ( $products ) : ?><div class="product-grid"><?php foreach ( $products as $product ) : ?><article class="product-card"><a href="<?php echo esc_url( $product->get_permalink() ); ?>"><?php pussypress_product_image( $product ); ?></a><div class="product-card-content"><h3><a href="<?php echo esc_url( $product->get_permalink() ); ?>"><?php echo esc_html( $product->get_name() ); ?></a></h3><p><?php echo esc_html( wp_trim_words( $product->get_short_description() ?: $product->get_description(), 14 ) ); ?></p><span class="price"><?php echo wp_kses_post( $product->get_price_html() ); ?></span><?php echo wp_kses_post( sprintf( '<a href="%s" data-quantity="1" class="button add_to_cart_button ajax_add_to_cart" data-product_id="%d" data-product_sku="%s" aria-label="Add %s to your cart">Add to cart</a>', esc_url( $product->add_to_cart_url() ), absint( $product->get_id() ), esc_attr( $product->get_sku() ), esc_attr( $product->get_name() ) ) ); ?></div></article><?php endforeach; ?></div><?php else : ?><p>No products are available yet. Add products in WooCommerce to populate this shelf.</p><?php endif; ?></div></section>
<section class="section purple" id="giveback"><div class="container giveback"><div><span class="kicker">The good stuff</span><h2>The purrfect donation 💛</h2><p class="lede">Ten percent of every order goes to vetted cat rescues and no-kill shelters — food, vet care, and safe places to wait for a forever home.</p></div><div class="stats"><div class="stat"><strong>10%</strong>of every order donated</div><div class="stat"><strong>100%</strong>no-kill shelters</div><div class="stat"><strong>$75+</strong>free shipping</div></div></div></section>
</main><?php get_footer(); ?>
