<?php
/** Pussycat Mart premium playful landing page powered by WooCommerce products. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
$products = function_exists( 'wc_get_products' ) ? wc_get_products( array( 'status' => 'publish', 'limit' => 4, 'orderby' => 'menu_order', 'order' => 'ASC' ) ) : array();
$image_url = function ( $file ) { return get_template_directory_uri() . '/assets/images/' . $file; };
?>
<main class="site-main" id="top">
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Happy cats. Brighter tomorrows.</p><h1>The <em>purr-fect</em> place<br>for spoiled cats.</h1><p class="lede">Shop toys, treats, and cozy picks your cat will love. A portion of every sale goes to no-kill cat shelters and rescues.</p><div class="hero-actions"><a class="button" href="#shop">Shop now <span aria-hidden="true">→</span></a><a class="button alt" href="#giveback">See your impact</a></div><div class="trust-row"><span><b>🚚</b><strong>Free shipping</strong><small>on orders $50+</small></span><span><b>♥</b><strong>Helps shelter cats</strong><small>with every order</small></span><span><b>🐾</b><strong>Happy cats</strong><small>happier tomorrows</small></span></div></div><div class="hero-visual"><img class="hero-image" src="<?php echo esc_url( $image_url( 'hero-cat.jpg' ) ); ?>" width="1600" height="1100" fetchpriority="high" decoding="async" alt="Toby the orange cat relaxing on a cozy blanket"><div class="hero-note"><strong>♥ Your order helps rescue cats</strong><span>Cloud Nap Cat Cave · $48.00</span><span>This order gives <b>$4.80</b> to no-kill shelters. <b>→</b></span></div></div></div></section>

<section class="section categories" aria-labelledby="categories-title"><div class="container"><div class="section-heading"><h2 id="categories-title">Shop by category <i>✦</i></h2><a class="text-link" href="<?php echo esc_url( function_exists( 'wc_get_page_permalink' ) ? wc_get_page_permalink( 'shop' ) : home_url( '/shop/' ) ); ?>">View all categories →</a></div><div class="category-grid"><a class="category-card category-toys" href="<?php echo esc_url( home_url( '/product-category/toys/' ) ); ?>"><img src="<?php echo esc_url( $image_url( 'product-toys.jpg' ) ); ?>" alt="Cat toys"><span><strong>Toys</strong><small>Play more. Purr more.</small></span><b>›</b></a><a class="category-card category-treats" href="<?php echo esc_url( home_url( '/product-category/treats/' ) ); ?>"><img src="<?php echo esc_url( $image_url( 'product-bowl.jpg' ) ); ?>" alt="Cat treats"><span><strong>Treats</strong><small>Tasty rewards for good cats.</small></span><b>›</b></a><a class="category-card category-scratchers" href="<?php echo esc_url( home_url( '/product-category/scratchers/' ) ); ?>"><img src="<?php echo esc_url( $image_url( 'product-scratcher.jpg' ) ); ?>" alt="Cat scratchers"><span><strong>Scratchers</strong><small>Healthy claws. Happier homes.</small></span><b>›</b></a><a class="category-card category-beds" href="<?php echo esc_url( home_url( '/product-category/beds/' ) ); ?>"><img src="<?php echo esc_url( $image_url( 'product-bed.jpg' ) ); ?>" alt="Cozy cat beds"><span><strong>Cozy beds</strong><small>Serious napping starts here.</small></span><b>›</b></a></div></div></section>

<section class="section featured" id="shop" aria-labelledby="featured-title"><div class="container"><div class="section-heading"><h2 id="featured-title">Featured products <i>✦</i></h2><a class="text-link" href="<?php echo esc_url( function_exists( 'wc_get_page_permalink' ) ? wc_get_page_permalink( 'shop' ) : home_url( '/shop/' ) ); ?>">View all products →</a></div><?php if ( $products ) : ?><div class="product-grid"><?php foreach ( $products as $product ) : ?><article class="product-card"><a class="product-image-link" href="<?php echo esc_url( $product->get_permalink() ); ?>"><?php pussypress_product_image( $product ); ?></a><div class="product-card-content"><h3><a href="<?php echo esc_url( $product->get_permalink() ); ?>"><?php echo esc_html( $product->get_name() ); ?></a></h3><span class="price"><?php echo wp_kses_post( $product->get_price_html() ); ?></span><div class="product-buy"><?php echo wp_kses_post( sprintf( '<a href="%s" data-quantity="1" class="button add_to_cart_button ajax_add_to_cart" data-product_id="%d" data-product_sku="%s" aria-label="Add %s to your cart">🛒</a>', esc_url( $product->add_to_cart_url() ), absint( $product->get_id() ), esc_attr( $product->get_sku() ), esc_attr( $product->get_name() ) ) ); ?></div></div></article><?php endforeach; ?></div><?php else : ?><p class="empty-state">Add published products in WooCommerce to populate this shelf.</p><?php endif; ?></div></section>

<section class="impact-strip" id="giveback"><div class="container impact-inner"><div class="impact-cat">🐈</div><div><h2>Every purchase gives back. <i>♥</i></h2><p>We show exactly how much your order donates to shelter and rescue partners.</p><details class="impact-example"><summary>See an example order</summary><div class="example-order"><div><strong>Cloud Nap Cat Cave</strong><span>1 × $48.00</span></div><div><span>Order total</span><strong>$48.00</strong></div><div class="example-donation"><span>10% shelter donation</span><strong>$4.80</strong></div></div></details><a class="button" href="#shop">Shop and make an impact →</a></div><div class="impact-paw">🐾</div></div></section>
<section class="section testimonials" id="giveback-details"><div class="container"><div class="section-heading"><div><h2>Toby approves <i>✦</i></h2><p class="section-copy">Real cats. Real happiness.</p></div><span class="approval">Now purr-chasing happiness. ♡</span></div><div class="testimonial-grid"><blockquote><span>★★★★★</span><p>“My cat is obsessed! Amazing quality and such a great mission.”</p><cite>— Lauren K.</cite></blockquote><blockquote><span>★★★★★</span><p>“Fast shipping, cute products, and I love that it helps rescues!”</p><cite>— Marcus T.</cite></blockquote><blockquote><span>★★★★★</span><p>“Toby would be proud. My kitty's new favorite store!”</p><cite>— Jenna R.</cite></blockquote></div></div></section>
</main><?php get_footer(); ?>
